const fs = require('fs')
const path = require('path')
const { Client } = require('pg')
const env = fs.readFileSync(path.join(__dirname, '..', '.env.local'), 'utf8')
const m = env.match(/^SUPABASE_DB_URL=(.+)$/m)
const connectionString = m[1].trim().replace(/^["']|["']$/g, '')
;(async () => {
  const c = new Client({ connectionString, ssl: { rejectUnauthorized: false } })
  await c.connect()
  console.log('=== distinct roles in profiles ===')
  console.log((await c.query('select role, count(*) from profiles group by role order by 2 desc')).rows)
  console.log('=== role check constraint on profiles ===')
  console.log((await c.query(`select conname, pg_get_constraintdef(oid) from pg_constraint where conrelid='public.profiles'::regclass and contype='c'`)).rows)
  console.log('=== profiles w/ club + role (email via auth.users) ===')
  console.log((await c.query(`select p.id, p.full_name, p.role, p.club_id, u.email from profiles p left join auth.users u on u.id=p.id order by p.created_at limit 30`)).rows)
  await c.end()
})().catch((e) => { console.error(e.message); process.exit(1) })
